name             "tiny_mon"
maintainer       "YOUR_NAME"
maintainer_email "YOUR_EMAIL"
license          "All rights reserved"
description      "Installs/Configures tiny_mon"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"

depends "apt"
depends "git"
depends "phantomjs"
depends "rvm"
depends "mysql"
depends "apache2"
depends "passenger_apache2"
